import Head from 'next/head'
import Link from 'next/link'
import {useRouter} from 'next/router'
import Home from '../../index';
import axios from 'axios';
import { useEffect, useState } from 'react';


export default function Categories() {
  const router=useRouter();
  const {id} =router.query;
  const [data,setData]=useState([]);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div>Categ {id}</div>
      <Home/>
      <div><Link href='/categories/2'>Categ 2</Link></div>
    </>
  )
}
