import Head from 'next/head'
import Link from 'next/link'
import CategorydropDown from '../components/CategorydropDown'
import Navbar from '../components/Navbar'
import NavbarController from '../components/NavbarController'

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <header>
      <div className="logoCon"><h3>OTOTECH</h3></div>
      <div className="linksCon">
      <Link href='#'>About Us</Link>
      <Link href='#'>Learn More</Link>
      <Link href='#'>Our Services</Link>
      <Link href='#'>Contact</Link>
      </div>
      <div className="buttonCon">
      <Link href='#'>HIRE A TALENT</Link>
            <NavbarController/>
      </div>

      </header>







<Navbar/>







      <div className="barCon">
        <CategorydropDown/>

      <div className="searchCon">
      <i className="fa fa-search"></i>
      <input type="text" name="search" placeholder="search topics, fields ..."/>
      </div>
      </div>

      <div className="filterCon">
			<div>Blog 1</div>
			<div>Blog 2</div>
			<div>Blog 3</div>
			<div>Blog 4</div>
		  </div>

      <div className="filterCon2">
			<div>Blog 1</div>
			<div>Blog 2</div>
			<div>Blog 3</div>
			<div>Blog 4</div>
			<div>Blog 5</div>
			<div>Blog 6</div>
		  </div>

      <div className="mainScreenCon">
      <div className="mainScreen">
      <div className="main1"><h3>OTOTECH BLOG</h3></div>
      <div className="main2"> <p>
      The Toptal Blog is the top hub for developers, designers, finance experts, executives, and entrepreneurs, featuring key technology updates, tutorials, freelancer resources, and management insights.
      </p></div>

      </div>

      <div className="submain">
      <div className="main3">
      <i className="fa fa-search"></i>
      <input type="text" name="search" placeholder="Search category, blogs, products ..."/>
      </div>
      <div className="main4">
      <div>Blog 1</div>
      <div>Blog 2</div>
      <div>Blog 3</div>
      <div>Blog 7</div>			
      </div>
      </div>
      </div>















      <div className='categoriesCon2'>
        <div className='categories'>
        <Link href='/categories'><a className='categoryCon'>
          <div className='categoryIcon'><i className='fa fa-globe'/></div>
          <div className='categoryInfo'>
            <h2>Enginneering</h2>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles</p>
          </div>
          </a>
        </Link>

        <Link href='/categories'><a className='categoryCon'>
          <div className='categoryIcon'><i className='fa fa-paint-brush'/></div>
          <div className='categoryInfo'>
            <h2>Graphics</h2>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles</p>
          </div>
          </a>
        </Link>

        <Link href='/categories'><a className='categoryCon'>
          <div className='categoryIcon'><i className='fa fa-desktop'/></div>
          <div className='categoryInfo'>
            <h2>Web Development</h2>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles</p>
          </div>
          </a>
        </Link>
      
        <Link href='/categories'><a className='categoryCon'>
          <div className='categoryIcon'><i className='fa fa-rocket'/></div>
          <div className='categoryInfo'>
            <h2>UI/UX Design</h2>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles</p>
          </div>
          </a>
        </Link>

        <Link href='/categories'><a className='categoryCon'>
          <div className='categoryIcon'><i className='fa fa-mobile'/></div>
          <div className='categoryInfo'>
            <h2>App Development</h2>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles</p>
          </div>
          </a>
        </Link>

        <Link href='/categories'><a className='categoryCon'>
          <div className='categoryIcon'><i className='fa fa-pencil'/></div>
          <div className='categoryInfo'>
            <h2>Content Writing</h2>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles</p>
          </div>
          </a>
        </Link>
        </div>
      </div>













      <div className='emailRegisterCon'>
        <div className='emailRegister'>
          <h2>World-class articles, delivered weekly.</h2>
          <form>
            <input type='email' placeholder='Enter your email'/>  
            <button>Submit</button>
          </form>
        </div>
      </div>















      <div className='categoriesCon3'>
      <div className='categories'>
        <Link href='#' ><a className='blogCon'>
          <div className='blogImg'><picture><img src='/OTOTECH2.jpg' alt='blog Categ'/></picture></div>
          <div className='blogInfo'>
          <h3>Content Writinkujyhtgrfegrvthbyjnukmilmkunjybhtgvrfthbjynukmil,o;limkunjyhg</h3>
          <p>by <span>STEVEN JOSEPH</span></p>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles
            </p> 
          </div>

          <div className='blogDataCon'>
            <div className='blogData'>
            <i className='fa fa-eye'><p>32</p></i>
            <i className='fa fa-thumbs-up'><p>22</p></i>
            </div>
            <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
          </div>
          </a>
        </Link>

        <Link href='#' ><a className='blogCon'>
          <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
          <div className='blogInfo'>
          <h3>Content Writing</h3>
          <p>by <span>STEVEN JOSEPH</span></p>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles
            </p> 
          </div>

          <div className='blogDataCon'>
            <div className='blogData'>
            <i className='fa fa-eye'><p>32</p></i>
            <i className='fa fa-thumbs-up'><p>22</p></i>
            </div>
            <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
          </div>
          </a>
        </Link>

        <Link href='#' ><a className='blogCon'>
          <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
          <div className='blogInfo'>
          <h3>Content Writing</h3>
          <p>by <span>STEVEN JOSEPH</span></p>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles
            </p> 
          </div>

          <div className='blogDataCon'>
            <div className='blogData'>
            <i className='fa fa-eye'><p>32</p></i>
            <i className='fa fa-thumbs-up'><p>22</p></i>
            </div>
            <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
          </div>
          </a>
        </Link>

        <Link href='#' ><a className='blogCon'>
          <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
          <div className='blogInfo'>
          <h3>Content Writing</h3>
          <p>by <span>STEVEN JOSEPH</span></p>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles
            </p> 
          </div>

          <div className='blogDataCon'>
            <div className='blogData'>
            <i className='fa fa-eye'><p>32</p></i>
            <i className='fa fa-thumbs-up'><p>22</p></i>
            </div>
            <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
          </div>
          </a>
        </Link>

        <Link href='#' ><a className='blogCon'>
          <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
          <div className='blogInfo'>
          <h3>Content Writing</h3>
          <p>by <span>STEVEN JOSEPH</span></p>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles
            </p> 
          </div>

          <div className='blogDataCon'>
            <div className='blogData'>
            <i className='fa fa-eye'><p>32</p></i>
            <i className='fa fa-thumbs-up'><p>22</p></i>
            </div>
            <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
          </div>
          </a>
        </Link>

        <Link href='#' ><a className='blogCon'>
          <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
          <div className='blogInfo'>
          <h3>Content Writing</h3>
          <p>by <span>STEVEN JOSEPH</span></p>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles
            </p> 
          </div>

          <div className='blogDataCon'>
            <div className='blogData'>
            <i className='fa fa-eye'><p>32</p></i>
            <i className='fa fa-thumbs-up'><p>22</p></i>
            </div>
            <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
          </div>
          </a>
        </Link>

        <Link href='#' ><a className='blogCon'>
          <div className='blogImg'><picture><img src='/OTOTECH2.jpg' alt='blog Categ'/></picture></div>
          <div className='blogInfo'>
          <h3>Content Writing</h3>
          <p>by <span>STEVEN JOSEPH</span></p>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles
            </p> 
          </div>

          <div className='blogDataCon'>
            <div className='blogData'>
            <i className='fa fa-eye'><p>32</p></i>
            <i className='fa fa-thumbs-up'><p>22</p></i>
            </div>
            <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
          </div>
          </a>
        </Link>

        <Link href='#' ><a className='blogCon'>
          <div className='blogImg'><picture><img src='/OTOTECH2.jpg' alt='blog Categ'/></picture></div>
          <div className='blogInfo'>
          <h3>Content Writing</h3>
          <p>by <span>STEVEN JOSEPH</span></p>
            <p>Explore in-depth developer tutorials and new technology 
              announcements created by professional engineers in the Toptal 
              network. Read engineering articles
            </p> 
          </div>

          <div className='blogDataCon'>
            <div className='blogData'>
            <i className='fa fa-eye'><p>32</p></i>
            <i className='fa fa-thumbs-up'><p>22</p></i>
            </div>
            <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
          </div>
          </a>
        </Link>
      </div>

      <div className='blogNavCon'>
        <div className='blogNav'>
        <Link href='#'>Previous</Link>
        <Link href='#'>Next</Link>
        <Link href='#'>1</Link>
        <Link href='#'>2</Link>
        <Link href='#'>3</Link>
        <Link href='#'>4</Link>
        <Link href='#'>5.....</Link>
        <Link href='#'>20</Link>
        </div>
      </div>
      </div>




img


      <div className='blogAdsCon'>
    <div className='blogAdsInfo'>
      <h2>IN NEED OF A WEBSITE, MOBILE APP, COPY WRITING SERVICES e.t.c ?<br/>
      VISIT US HERE TO GET A WORLD CLASS SERVICE</h2>
      <Link href='#'>OUR SERVICES</Link>
    </div>
    <div className='blogAdsImg'>
      <picture><img src='/OTOTECH3.png' alt='blog Ads'/></picture>
    </div>
  </div>




    <div className='blogSliderHeading'><h2>Most Read Articles</h2></div>

  <div className='blogSliderCon'>
    <div className='blogSlider'>
    <Link href='#' ><a className='blogCon'>
      <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
      <div className='blogInfo'>
      <h3>Content Writing</h3>
      <p>by <span>STEVEN JOSEPH</span></p>
        <p>Explore in-depth developer tutorials and new technology 
          announcements created by professional engineers in the Toptal 
          network. Read engineering articles
        </p> 
      </div>

      <div className='blogDataCon'>
        <div className='blogData'>
        <i className='fa fa-eye'><p>32</p></i>
        <i className='fa fa-thumbs-up'><p>22</p></i>
        </div>
        <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
      </div>
      </a>
    </Link>
    <Link href='#' ><a className='blogCon'>
      <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
      <div className='blogInfo'>
      <h3>Content Writing</h3>
      <p>by <span>STEVEN JOSEPH</span></p>
        <p>Explore in-depth developer tutorials and new technology 
          announcements created by professional engineers in the Toptal 
          network. Read engineering articles
        </p> 
      </div>

      <div className='blogDataCon'>
        <div className='blogData'>
        <i className='fa fa-eye'><p>32</p></i>
        <i className='fa fa-thumbs-up'><p>22</p></i>
        </div>
        <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
      </div>
      </a>
    </Link>
    <Link href='#' ><a className='blogCon'>
      <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
      <div className='blogInfo'>
      <h3>Content Writing</h3>
      <p>by <span>STEVEN JOSEPH</span></p>
        <p>Explore in-depth developer tutorials and new technology 
          announcements created by professional engineers in the Toptal 
          network. Read engineering articles
        </p> 
      </div>

      <div className='blogDataCon'>
        <div className='blogData'>
        <i className='fa fa-eye'><p>32</p></i>
        <i className='fa fa-thumbs-up'><p>22</p></i>
        </div>
        <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
      </div>
      </a>
    </Link>
    <Link href='#' ><a className='blogCon'>
      <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
      <div className='blogInfo'>
      <h3>Content Writing</h3>
      <p>by <span>STEVEN JOSEPH</span></p>
        <p>Explore in-depth developer tutorials and new technology 
          announcements created by professional engineers in the Toptal 
          network. Read engineering articles
        </p> 
      </div>

      <div className='blogDataCon'>
        <div className='blogData'>
        <i className='fa fa-eye'><p>32</p></i>
        <i className='fa fa-thumbs-up'><p>22</p></i>
        </div>
        <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
      </div>
      </a>
    </Link>
    <Link href='#' ><a className='blogCon'>
      <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
      <div className='blogInfo'>
      <h3>Content Writing</h3>
      <p>by <span>STEVEN JOSEPH</span></p>
        <p>Explore in-depth developer tutorials and new technology 
          announcements created by professional engineers in the Toptal 
          network. Read engineering articles
        </p> 
      </div>

      <div className='blogDataCon'>
        <div className='blogData'>
        <i className='fa fa-eye'><p>32</p></i>
        <i className='fa fa-thumbs-up'><p>22</p></i>
        </div>
        <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
      </div>
      </a>
    </Link>
            <Link href='#' ><a className='blogCon'>
      <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
      <div className='blogInfo'>
      <h3>Content Writing</h3>
      <p>by <span>STEVEN JOSEPH</span></p>
        <p>Explore in-depth developer tutorials and new technology 
          announcements created by professional engineers in the Toptal 
          network. Read engineering articles
        </p> 
      </div>

      <div className='blogDataCon'>
        <div className='blogData'>
        <i className='fa fa-eye'><p>32</p></i>
        <i className='fa fa-thumbs-up'><p>22</p></i>
        </div>
        <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
      </div>
      </a>
    </Link>
    <Link href='#' ><a className='blogCon' style={{width: "300px"}}>
      <div className='blogImg'><picture><img src='/OTOTECH1.jpg'/> </picture></div>
      <div className='blogInfo'>
      <h3>Content Writing</h3>
      <p>by <span>STEVEN JOSEPH</span></p>
        <p>Explore in-depth developer tutorials and new technology 
          announcements created by professional engineers in the Toptal 
          network. Read engineering articles
        </p> 
      </div>

      <div className='blogDataCon'>
        <div className='blogData'>
        <i className='fa fa-eye'><p>32</p></i>
        <i className='fa fa-thumbs-up'><p>22</p></i>
        </div>
        <div className='blogRead'><Link href='#'><p>Read</p></Link></div>
      </div>
      </a>
    </Link>
    </div>
  </div>







  <footer>
    <div className='footerCon'>
      <div className='footerLinksCon'>
        <h4>OTOTECH Industries</h4>
        <p> For more enquires and service placement please feel free to
           contact us through the following Social media's.</p>
           <ul>
           <li><Link href='#'><i className='fa fa-facebook'></i></Link></li>
           <li><Link href='#'><i className='fa fa-phone'></i></Link></li>
           <li><Link href='#'><i className='fa fa-linkedin'></i></Link></li>
           <li><Link href='#'><i className='fa fa-whatsapp'></i></Link></li>
           <li><Link href='#'><i className='fa fa-google'></i></Link></li>
           <li><Link href='#'><i className='fa fa-envelope'></i></Link></li>
           </ul>
      </div>

      <div className='footerLinksCon'>
        <h4>Additional Pages</h4>
        <ol>
        <li><Link href='#'>About Us</Link></li>
        <li><Link href='#'>How We Work</Link></li>
        <li><Link href='#'>Quick Support</Link></li>
        <li><Link href='#'>Privacy Policy</Link></li>
        </ol>
      </div>

      <div className='footerLinksCon'>
        <h4>Useful Links</h4>
        <ol>
        <li><Link href='#'>Page Privacy</Link></li>
        <li><Link href='#'>Lincences and Registration</Link></li>
        </ol>
      </div>
      
      <div className='footerLinksCon'>
        <h4>Contact Us</h4>
        <form>
        <input type='text' placeholder='Full Name'/>
        <input type='email' placeholder='E-Mail Address'/>
        <textarea placeholder='Your Message'>

        </textarea>
        <button>SEND MESSAGE</button>
        </form>
      </div>
    </div>
  </footer>
  <div className='footerCon2'><p>Copyright © 2022 OTOTECH Industries.</p></div>
    </>
  )
}
